Lightweight.Caching/Lru/ConcurrentLru.cs
Lightweight.Caching/Lru/ConcurrentLruTemplate.cs
Lightweight.Caching/Lru/ConcurrentTLru.cs
Lightweight.Caching/Lru/FastConcurrentLru.cs
Lightweight.Caching/Lru/FastConcurrentTLru.cs
README.md

Name the LRU classes with no metrics 'faster'

fast naming convention

---

.github/workflows/dotnet-core.yml
BitFaster.Caching/BitFaster.Caching.csproj

Target:
- .NET Framework 4.72 and 4.8
- .NET Standard 2.0
- .NET Core 2.0, 3.0 and 3.1

multi target

---

BitFaster.Caching.UnitTests/Lru/ClassicLruTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching/ICache.cs
BitFaster.Caching/Lru/ClassicLru.cs
BitFaster.Caching/Lru/LruItem.cs
BitFaster.Caching/Lru/TemplateConcurrentLru.cs

Implement TryUpdate, which does not affect LRU order.

Implement TryUpdate

---

BitFaster.Caching.Benchmarks/BitFaster.Caching.Benchmarks.csproj
BitFaster.Caching.HitRateAnalysis/BitFaster.Caching.HitRateAnalysis.csproj
BitFaster.Caching.ThroughputAnalysis/BitFaster.Caching.ThroughputAnalysis.csproj
BitFaster.Caching/BitFaster.Caching.csproj

NuGet package includes .NET 5 build target. All .exe's re-targeted to .NET 5.

Target .NET 5

---

BitFaster.Caching.UnitTests/AssemblyInitialize.cs
BitFaster.Caching.UnitTests/ReferenceCountTests.cs
BitFaster.Caching.UnitTests/SingletonCacheTests.cs
BitFaster.Caching/BitFaster.Caching.csproj
BitFaster.Caching/ReferenceCount.cs
BitFaster.Caching/SingletonCache.cs

Race condition in dispose logic.

Fix object disposed exception in SingletonCache.Release 

---

BitFaster.Caching.UnitTests/Lru/ClassicLruTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching/ICache.cs
BitFaster.Caching/Lru/ClassicLru.cs
BitFaster.Caching/Lru/TemplateConcurrentLru.cs

Provide a method to clear the cache.

Implement clear

---

BitFaster.Caching/BitFaster.Caching.csproj

bump to 1.0.4

---

BitFaster.Caching/BitFaster.Caching.csproj

Small part of making automated package publish.
This describes how to run an action when publishing a tag of the form 'v#.#.#':
https://acraven.medium.com/a-nuget-package-workflow-using-github-actions-7da8c6557863

Deterministic Build

---

BitFaster.Caching/Lru/TemplateConcurrentLru.cs

seems cleaner, small reduction in code size.

prefer loop to recurse

---

BenchmarkDotNet.AsmSlicer/AsmFileProcessor.cs
BenchmarkDotNet.AsmSlicer/BenchMethodAsmWriter.cs
BenchmarkDotNet.AsmSlicer/BenchmarkDotNet.AsmSlicer.csproj
BenchmarkDotNet.AsmSlicer/Program.cs
BenchmarkDotNet.AsmSlicer/Properties/launchSettings.json
BitFaster.Caching.Benchmarks/BitFaster.Caching.Benchmarks.csproj
BitFaster.Caching.Benchmarks/DataStructureBenchmarks.cs
BitFaster.Caching.Benchmarks/DisposerBench.cs
BitFaster.Caching.Benchmarks/Lru/LruCycleBench.cs
BitFaster.Caching.Benchmarks/Lru/LruJustGetOrAdd.cs
BitFaster.Caching.Benchmarks/Lru/LruJustTryGet.cs
BitFaster.Caching.Benchmarks/Lru/LruMultiGet.cs
BitFaster.Caching.Benchmarks/Lru/LruZipDistribution.cs
BitFaster.Caching.Benchmarks/Lru/TLruTimeBenchmark.cs
BitFaster.Caching.Benchmarks/TimeBenchmarks.cs
BitFaster.sln
benchrunner.cmd

- Run benchmarks against both .net48 and .net60
- Add a cmd script to run all the benchmarks
- Add a program to break down the asm into diffable files to compare impact of changes

multi bench

---

.github/workflows/dotnet-core.yml

https://github.com/actions/upload-artifact

publish artifacts on builds

---

.github/workflows/dotnet-core.yml
.github/workflows/pr.yml
.github/workflows/push.yml
BitFaster.Caching.UnitTests/BitFaster.Caching.UnitTests.csproj

https://samlearnsazure.blog/2021/01/05/code-coverage-in-github-with-net-core/
[![Coverage Status](https://coveralls.io/repos/github/bitfaster/BitFaster.Caching/badge.svg?branch=main)](https://coveralls.io/github/bitfaster/BitFaster.Caching?branch=main)
https://coveralls.io/github/bitfaster/BitFaster.Caching

collect code coverage

---

BitFaster.Caching.HitRateAnalysis/Wikibench/WikiBenchFile.cs

fix warning

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuTests.cs
BitFaster.Caching/Lfu/ConcurrentLfu.cs
BitFaster.Caching/Lfu/LfuNode.cs
BitFaster.Caching/Lfu/LfuNodeList.cs

Implement the correct TinyLfu policy.

TinyLfu policy

---

BitFaster.Caching.HitRateAnalysis/BitFaster.Caching.HitRateAnalysis.csproj
BitFaster.Caching.ThroughputAnalysis/BitFaster.Caching.ThroughputAnalysis.csproj

NoWarn NU1701

---

BitFaster.Caching.ThroughputAnalysis/BitFaster.Caching.ThroughputAnalysis.csproj
BitFaster.Caching.ThroughputAnalysis/Program.cs

Use benchmarkdotnet to print the environment info:

print env info

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuTests.cs
BitFaster.Caching/Lfu/ConcurrentLfu.cs
BitFaster.Caching/Lfu/LfuNode.cs

Differentiate between items that are marked for removal, and those that are actually removed.

count evictions

---

BitFaster.Caching.Benchmarks/Lfu/LfuJustGetOrAdd.cs
BitFaster.Caching.Benchmarks/Lru/LruJustGetOrAdd.cs
BitFaster.Caching.HitRateAnalysis/Analysis.cs
BitFaster.Caching.ThroughputAnalysis/Program.cs
BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuBuilderTests.cs
BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuTests.cs
BitFaster.Caching/Lfu/Builder/LfuBuilderBase.cs
BitFaster.Caching/Lfu/Builder/LfuInfo.cs
BitFaster.Caching/Lfu/ConcurrentLfu.cs
BitFaster.Caching/Lfu/ConcurrentLfuBuilder.cs
BitFaster.Caching/Lfu/LfuNode.cs
BitFaster.Caching/Lfu/LfuNodeList.cs

Implement a builder for ConcurrentLfu

basic lfu builder

---

BitFaster.Caching.ThroughputAnalysis/BitFaster.Caching.ThroughputAnalysis.csproj
BitFaster.Caching.ThroughputAnalysis/MemoryCacheAdaptor.cs
BitFaster.Caching.ThroughputAnalysis/Program.cs

memorycache

---

BitFaster.Caching/BitFaster.Caching.csproj

Add the missing XML documentation file to the NuGet package.

intellisense

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuTests.cs
BitFaster.Caching/Lfu/ConcurrentLfu.cs

Rename `PendingMaintenance()` => `DoMaintenance()`.

domaintenance

---

BitFaster.Caching/Lfu/ConcurrentLfu.cs

Dispose new items created but not added to the LFU.

dispose on race

---

.github/workflows/gate.yml
BitFaster.Caching.UnitTests/BitFaster.Caching.UnitTests.csproj

Reverts bitfaster/BitFaster.Caching#317

Revert "fix mac coverage collection"

---

BitFaster.Caching/BitFaster.Caching.csproj

Validate against 2.2 API surface going forward.

validate against 2.2

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuTests.cs
BitFaster.Caching.UnitTests/Lru/ClassicLruTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs

Fix Infer ConfigureAwait test warnings

---

BitFaster.Caching/Lfu/ConcurrentLfu.cs

https://arbel.net/2013/02/03/best-practices-for-using-concurrentdictionary/

lfu no lock count

---

BitFaster.Caching.UnitTests/Atomic/ScopedAtomicFactorySoakTests.cs
BitFaster.Caching/Atomic/ScopedAtomicFactory.cs

Include a second test where items are deleted to cover races between adding/removing.

soak test ScopedAtomicFactory

---

BitFaster.Caching/Lfu/ConcurrentLfu.cs

Tiny optimization to the loop - marshal the list as span.

use CollectionsMarshal.AsSpan for LFU trim

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuSoakTests.cs

Standardize test parameters and de-dupe the setup code.

Lfu soak test cleanup

---

BitFaster.Caching.UnitTests/CachePolicyTests.cs
BitFaster.Caching/CachePolicy.cs

This is not really that useful and adding more API surface, so remove.

Remove CachePolicy TryTrimExpired

---

BitFaster.Caching/ReadMe.md

Add a note about time-based expiry, with a link to the wiki.

Update pkg readme

---

BitFaster.Caching/BitFaster.Caching.csproj

Package validation now based on v2.4.0.

Validate 2.4

---

BitFaster.Caching/IAsyncCache.cs
BitFaster.Caching/ICache.cs
BitFaster.Caching/IScopedAsyncCache.cs
BitFaster.Caching/IScopedCache.cs

Default impl has caused confusion, add clarifying docs.

Add docs around TArg methods

---

.github/workflows/gate.yml
.github/workflows/testreport.yml

Tests now upload trx files containing test results, a post build job then generates the test reports from the .trx files.

Refactor test report

---

BitFaster.Caching.UnitTests/DurationTests.cs
BitFaster.Caching/Duration.cs

Add convenience methods for Duration

---

BitFaster.Caching/ReadMe.md

`ConcurrentLfu` now supports time based expiry, link to docs.

Update package readme

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuCoreTests.cs
BitFaster.Caching.UnitTests/Lfu/ConcurrentTLfuTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruAfterAccessTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentTLruTests.cs

Retry time-based tests

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuCoreTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruAfterDiscreteTests.cs
BitFaster.Caching.UnitTests/Lru/TlruStopwatchPolicyTests.cs
BitFaster.Caching.UnitTests/Lru/TlruTicksPolicyTests.cs

Improve stability for local test runs.

Extend test wait

---

BitFaster.Caching.UnitTests/Retry/RetryFact.cs

Restore missing code coverage.

Fix assembly name for RetryFact
