bitfaster/BitFaster.Caching

BitFaster.Caching/SingletonCache.cs
BitFaster.Caching/SingletonCacheExtensions.cs

Support custom value factory as well as new TValue()

extend singletoncache

---

BitFaster.Caching.Benchmarks/Lru/ZipDistribution.cs
BitFaster.Caching.Benchmarks/Program.cs
BitFaster.Sampling/BitFaster.Sampling.csproj
BitFaster.Sampling/Program.cs
BitFaster.sln
README.md

Add tests based on zipf data distribution.

zipf distribution

---

BitFaster.Caching.Benchmarks/BitFaster.Caching.Benchmarks.csproj
BitFaster.Caching.Benchmarks/Program.cs
BitFaster.Caching.HitRateAnalysis/BitFaster.Caching.HitRateAnalysis.csproj
BitFaster.Caching.UnitTests/Lru/TlruDateTimePolicyTests.cs
BitFaster.Caching.UnitTests/Lru/TlruTicksPolicyTests.cs
BitFaster.Caching/Lru/ConcurrentTLru.cs
BitFaster.Caching/Lru/FastConcurrentTLru.cs
BitFaster.Caching/Lru/TickCountLruItem.cs
BitFaster.Caching/Lru/TlruDateTimePolicy.cs
BitFaster.Caching/Lru/TlruTicksPolicy.cs

This results in TLru policy being extremely close in speed to Lru.

measure time with Environment.TickCount

---

BitFaster.Caching/Lru/TemplateConcurrentLru.cs
README.md

Before:
|                Method |      Mean |    Error |   StdDev | Ratio |  Gen 0 | Allocated |
|---------------------- |----------:|---------:|---------:|------:|-------:|----------:|
|  ConcurrentDictionary |  16.88 ns | 0.276 ns | 0.245 ns |  1.00 |      - |         - |
|     FastConcurrentLru |  23.27 ns | 0.491 ns | 0.565 ns |  1.38 |      - |         - |
|         ConcurrentLru |  26.77 ns | 0.512 ns | 0.666 ns |  1.60 |      - |         - |
|    FastConcurrentTLru |  54.35 ns | 0.650 ns | 0.576 ns |  3.22 |      - |         - |
|        ConcurrentTLru |  60.10 ns | 1.024 ns | 1.501 ns |  3.53 |      - |         - |
|            ClassicLru |  68.04 ns | 1.400 ns | 2.221 ns |  4.12 |      - |         - |
|    RuntimeMemoryCache | 280.16 ns | 5.607 ns | 7.486 ns | 16.59 | 0.0153 | …

Inline policy/move logic

---

BitFaster.Caching.UnitTests/Lru/ClassicLruTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching/ICache.cs
BitFaster.Caching/Lru/ClassicLru.cs
BitFaster.Caching/Lru/TemplateConcurrentLru.cs

Implement GetOrAdd.
Only new items will affect LRU order. Considered adding a flag to control whether the item is touched, but flag params are [evil](https://martinfowler.com/bliki/FlagArgument.html). There is some precedent for only updating the LRU order for new items - this is the same way [add ](https://github.com/memcached/memcached/wiki/Commands#add)and [replace](https://github.com/memcached/memcached/wiki/Commands#replace) work in the memcached API.

Implement GetOrAdd

---

BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching/Lru/TemplateConcurrentLru.cs

Summary:
1. Update LRU removal logic, use the [atomic remove method from ICollection](https://devblogs.microsoft.com/pfxteam/little-known-gems-atomic-conditional-removals-from-concurrentdictionary/)
2. Dispose previous items on update if value is IDisposable
The atomic remove based on the reference to the existing item mitigates this race scenario because LruItem1 and LruItem1* will be different memory references (thus Thread C cannot remove LruItem1*):
> Thread A TryRemove(1), removes LruItem1, has reference to removed item but not yet marked as removed
> Thread B GetOrAdd(1) => Adds LruItem1*
> Thread C GetOrAdd(2), Cycle, Move(LruItem1, Removed)
> Thread C can run and remove LruItem1* from this.dictionary before Thread A has marked LruItem1 as removed.
> In this situation, a subsequent …

LRU: atomic ConcurrentDictionary.Remove()

---

BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching/Lru/TemplateConcurrentLru.cs

When the ctor capacity arg is not divisible by 3, actual ConcurrentLru capacity is less than the specified amount. 
Internally, there are 3 queues, and each queue size = capacity/3.
All items are guaranteed to flow through hot and cold at least once, so fix is to pad the cold and hot queues.

Fix ctor rounding

---

BitFaster.Caching/Lru/TemplateConcurrentLru.cs

New items that are not added are not disposed correctly.

Dispose on race during GetOrAdd

---

BitFaster.Caching.Benchmarks/Lru/LruJustGetOrAdd.cs
BitFaster.Caching/Disposer.cs
BitFaster.Caching/Lru/ClassicLru.cs
BitFaster.Caching/Lru/TemplateConcurrentLru.cs

- Fix incorrect arg exception call sites
- Simplify default(T)
- Simplify decomposition
- Simplify ctor call sites
- Add missing code comment docs on Disposer

code cleanup

---

BitFaster.Caching.UnitTests/ScopedTests.cs
BitFaster.Caching/Scoped.cs

- Provide TryCreateLifetime
- Fix race in create lifetime it is possible for reference count to reach zero

fix scoped race

---

BenchmarkDotNet.AsmSlicer/BenchMethodAsmWriter.cs

Also generate a method size summary, with stable order that can be diffed.
E.g.
| #  | Method      | Size (bytes) |
| -- | ----------- | ------------ |
| 0 | BitFaster.Caching.Benchmarks.Lru.LruCycleBench.ConcurrentLruEvent | 175 |
| 1 | BitFaster.Caching.Benchmarks.Lru.LruCycleBench+<>c.<ConcurrentLruEvent>b__11_0(Int32 | 3 |
| 2 | BitFaster.Caching.Lru.TemplateConcurrentLru`5[[System.Int32, System.Private.CoreLib],[System.Int32, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib],[BitFaster.Caching.Lru.LruPolicy`2[[System.Int32, System.Private.CoreLib],[System.Int32, System.Private.CoreLib]], BitFaster.Caching],[BitFaster.Caching.Lru.HitCounter`2[[System.Int32, System.Private.CoreLib],[System.Int32, System.Private.CoreLib]], BitFaster.Caching]].Cycle | 905 |
| 3 | …

summarize JITted method size

---

BitFaster.Caching.UnitTests/Lru/ClassicLruTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching/Lru/ClassicLru.cs
BitFaster.Caching/Lru/TemplateConcurrentLru.cs

Enable enumeration of key value pairs.

Cache implements IEnumerable<KeyValuePair<K, V>>

---

BitFaster.Caching.HitRateAnalysis.Wikibench/Analysis.cs
BitFaster.Caching.HitRateAnalysis.Wikibench/BitFaster.Caching.HitRateAnalysis.Wikibench.csproj
BitFaster.Caching.HitRateAnalysis.Wikibench/Program.cs
BitFaster.Caching.HitRateAnalysis.Wikibench/WikiBenchFile.cs
BitFaster.Caching.HitRateAnalysis.Wikibench/WikiDataSet.cs
BitFaster.sln

Implement a simple test harness to analyze hit rate using the wikibench data set.
```
Tested 44,846,065 URIs in 00:06:25.4379518
Size 25 Classic HitRate 12.34% Concurrent HitRate 30.75%
Size 50 Classic HitRate 21.44% Concurrent HitRate 38.54%
Size 75 Classic HitRate 27.84% Concurrent HitRate 42.52%
Size 100 Classic HitRate 32.26% Concurrent HitRate 45.10%
Size 125 Classic HitRate 35.31% Concurrent HitRate 47.22%
Size 150 Classic HitRate 37.48% Concurrent HitRate 48.69%
Size 175 Classic HitRate 39.10% Concurrent HitRate 49.93%
Size 200 Classic HitRate 40.36% Concurrent HitRate 50.83%
```

analyze hit rate from wikibench

---

BitFaster.Caching.HitRateAnalysis/Arc/Analysis.cs
BitFaster.Caching.HitRateAnalysis/Arc/ArcDataFile.cs
BitFaster.Caching.HitRateAnalysis/Arc/Runner.cs
BitFaster.Caching.HitRateAnalysis/Arc/RunnerConfig.cs
BitFaster.Caching.HitRateAnalysis/Glimpse/DataFile.cs
BitFaster.Caching.HitRateAnalysis/Program.cs

Analyze hit rate for ARC workloads. Slight edge for OLTP, not better than LRU for Database and Search as cache size increases.
Tested 914145 keys in 00:00:07.4416965
Size 250 Classic HitRate 16.47% Concurrent HitRate 15.31%
Size 500 Classic HitRate 23.45% Concurrent HitRate 26.88%
Size 750 Classic HitRate 28.28% Concurrent HitRate 32.04%
Size 1000 Classic HitRate 32.83% Concurrent HitRate 35.36%
Size 1250 Classic HitRate 36.21% Concurrent HitRate 37.97%
Size 1500 Classic HitRate 38.70% Concurrent HitRate 40.06%
Size 1750 Classic HitRate 40.79% Concurrent HitRate 41.88%
Size 2000 Classic HitRate 42.47% Concurrent HitRate 43.49%
Tested 43704979 keys in 00:14:02.7199790
Size 1000000 Classic HitRate 3.09% Concurrent HitRate 4.22%
Size 2000000 Classic HitRate 10.74% Concurrent HitRate 4.66% …

test arc workloads

---

BitFaster.Caching.HitRateAnalysis/Arc/Analysis.cs
BitFaster.Caching.HitRateAnalysis/Arc/Runner.cs
BitFaster.Caching.HitRateAnalysis/Glimpse/Analysis.cs
BitFaster.Caching.HitRateAnalysis/Glimpse/Runner.cs
BitFaster.Caching.HitRateAnalysis/ResultExtensions.cs
BitFaster.Caching.HitRateAnalysis/Wikibench/Analysis.cs
BitFaster.Caching.HitRateAnalysis/Wikibench/Runner.cs
BitFaster.Caching.HitRateAnalysis/Zipfian/AnalysisResult.cs
BitFaster.Caching.HitRateAnalysis/Zipfian/Runner.cs

Console output as markdown table, e.g.
| CacheSize | ConcurrentLruHitRate |  ClassicLruHitRate |
|-----------|----------------------|--------------------|
|       250 |   15.314747660382105 | 16.473425988218498 |
|       500 |    26.88391885313599 | 23.445405269404745 |
|       750 |    32.04305662668395 |  28.28074320813438 |
|      1000 |   35.357738651964404 |  32.83089663018449 |
|      1250 |    37.96881238753152 | 36.209682271412085 |
|      1500 |    40.05600862007668 |  38.69604931383971 |
|      1750 |   41.877710866438036 |   40.7881681790088 |
|      2000 |    43.49200619157792 |  42.46973948334236 |

write tables as markdown

---

BitFaster.Caching/ScopedCache.cs

seal scopedcache

---

BitFaster.Caching.UnitTests/Lru/ClassicLruTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching.UnitTests/Lru/NoTelemetryPolicyTests.cs
BitFaster.Caching.UnitTests/Lru/TelemetryPolicyTests.cs
BitFaster.Caching/ICacheMetrics.cs
BitFaster.Caching/Lru/ClassicLru.cs
BitFaster.Caching/Lru/NoTelemetryPolicy.cs
BitFaster.Caching/Lru/TelemetryPolicy.cs

count evicted

---

BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching/Lru/NoTelemetryPolicy.cs
BitFaster.Caching/Lru/TelemetryPolicy.cs
BitFaster.Caching/Lru/TemplateConcurrentLru.cs

Enable passing around a reference to the Metrics. Previously this failed because the backing impl is a struct and when it is mutated after it was copied, all changes are lost.
By storing all the data in a reference type, the struct is effectively immutable (after the ref type is created).

enable metrics ref

---

BitFaster.Caching.UnitTests/Synchronized/AsyncAtomicFactoryTests.cs
BitFaster.Caching.UnitTests/Synchronized/AtomicFactoryTests.cs
BitFaster.Caching.UnitTests/Synchronized/ScopedAsyncAtomicFactoryTests.cs
BitFaster.Caching.UnitTests/Synchronized/ScopedAtomicFactoryTests.cs
BitFaster.Caching/Synchronized/AsyncAtomicFactory.cs
BitFaster.Caching/Synchronized/AtomicFactory.cs
BitFaster.Caching/Synchronized/ScopedAsyncAtomicFactory.cs
BitFaster.Caching/Synchronized/ScopedAtomicFactory.cs

atomicfactory

---

BitFaster.Caching.UnitTests/CacheEventProxyBaseTests.cs
BitFaster.Caching.UnitTests/ScopedCacheTestBase.cs
BitFaster.Caching.UnitTests/ScopedCacheTests.cs
BitFaster.Caching.UnitTests/Synchronized/AtomicFactoryAsyncCacheTests.cs
BitFaster.Caching.UnitTests/Synchronized/AtomicFactoryCacheTests.cs
BitFaster.Caching.UnitTests/Synchronized/AtomicFactoryScopedAsyncCacheTests.cs
BitFaster.Caching.UnitTests/Synchronized/AtomicFactoryScopedCacheTests.cs
BitFaster.Caching.UnitTests/Synchronized/ScopedAsyncAtomicFactoryTests.cs
BitFaster.Caching.UnitTests/Synchronized/ScopedAtomicFactoryTests.cs
BitFaster.Caching/CacheEventProxyBase.cs
BitFaster.Caching/ScopedCache.cs
BitFaster.Caching/ScopedCacheDefaults.cs
BitFaster.Caching/Synchronized/AsyncAtomicFactory.cs
BitFaster.Caching/Synchronized/AtomicFactory.cs
BitFaster.Caching/Synchronized/AtomicFactoryAsyncCache.cs
BitFaster.Caching/Synchronized/AtomicFactoryCache.cs
BitFaster.Caching/Synchronized/AtomicFactoryScopedAsyncCache.cs
BitFaster.Caching/Synchronized/AtomicFactoryScopedCache.cs
BitFaster.Caching/Synchronized/ScopedAsyncAtomicFactory.cs
BitFaster.Caching/Synchronized/ScopedAtomicFactory.cs

Provide adaptors so that atomic value factories can be used with ICache and IScopedCache.

decorators for atomic value factories

---

BitFaster.Caching.Benchmarks/Lru/LruJustGetOrAdd.cs

Test cache hit perf:
|                   Method |            Runtime |       Mean |     Error |    StdDev | Ratio | Code Size | Allocated |
|------------------------- |------------------- |-----------:|----------:|----------:|------:|----------:|----------:|
|     ConcurrentDictionary |           .NET 6.0 |   7.464 ns | 0.1457 ns | 0.1292 ns |  1.00 |   1,523 B |         - |
|        FastConcurrentLru |           .NET 6.0 |  10.086 ns | 0.0920 ns | 0.0768 ns |  1.36 |   2,352 B |         - |
|            ConcurrentLru |           .NET 6.0 |  13.762 ns | 0.1698 ns | 0.1418 ns |  1.85 |   2,378 B |         - |
|            AtomicFastLru |           .NET 6.0 |  19.864 ns | 0.3901 ns | 0.3458 ns |  2.66 |     846 B |         - |
|       FastConcurrentTLru |           .NET 6.0 |  25.805 ns | …

bench atomic factory get

---

BitFaster.Caching.Benchmarks/Lru/LruAsyncGet.cs
BitFaster.Caching.Benchmarks/Lru/LruJustGetOrAdd.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruBuilderTests.cs
BitFaster.Caching/Lru/Builder/AtomicAsyncConcurrentLruBuilder.cs
BitFaster.Caching/Lru/Builder/AtomicConcurrentLruBuilder.cs
BitFaster.Caching/Lru/Builder/AtomicScopedAsyncConcurrentLruBuilder.cs
BitFaster.Caching/Lru/Builder/AtomicScopedConcurrentLruBuilder.cs
BitFaster.Caching/Lru/Builder/ScopedAsyncConcurrentLruBuilder.cs
BitFaster.Caching/Lru/Builder/ScopedConcurrentLruBuilder.cs
BitFaster.Caching/Lru/ConcurrentLruBuilder.cs
BitFaster.Caching/Lru/ConcurrentLruBuilderExtensions.cs

Name builder types with a consistent order:
async => cache
scoped => async
atomic => scoped, async
Rename builder extension methods so that methods changing the cache type have prefix 'As', and configuration methods have prefix 'With', e.g.
```cs
var lru = new ConcurrentLruBuilder<int, Disposable>()
.WithAtomicValueFactory()
.AsAsyncCache()
.AsScopedCache()
.WithCapacity(3)
.Build();
```
Add descriptive comments to the builder extension methods making it easier to use.

cleanup builders

---

BitFaster.Caching.UnitTests/Atomic/AtomicFactoryAsyncCacheTests.cs
BitFaster.Caching.UnitTests/Atomic/AtomicFactoryCacheTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruBuilderTests.cs
BitFaster.Caching.UnitTests/ScopedCacheTestBase.cs
BitFaster.Caching/Atomic/AtomicFactoryAsyncCache.cs
BitFaster.Caching/Atomic/AtomicFactoryCache.cs
BitFaster.Caching/Atomic/AtomicFactoryScopedCache.cs
BitFaster.Caching/ICache.cs
BitFaster.Caching/IScopedCache.cs
BitFaster.Caching/ScopedCache.cs

Capacity is moved to the eviction policy, remove redundant properties.

rem capacity

---

BitFaster.Caching/Lfu/ConcurrentLfu.cs

Missed a detail in the evictFromMain logic.
This slightly changes the Wikipedia hit rate result, it is slightly better for every cache size except 150 and 175:
| CacheSize |  ClassicLruHitRate | ConcurrentLruHitRate | ConcurrentLfuHitRate |
|-----------|--------------------|----------------------|----------------------|
|        25 | 12.339894258281078 |   30.750918726091133 |   29.036389257340637 |
|        50 | 21.441939220308402 |    38.53943261242653 |   37.330211691928824 |
|        75 |  27.84286871100062 |    42.52255799923583 |    41.40486350363181 |
|       100 |  32.25609649363885 |    45.09773154010279 |   44.030016903378254 |
|       125 |  35.30941454952625 |   47.217255293190156 |     45.7745936014676 |
|       150 | 37.484624347754924 |    48.69152956898225 | …

fix eviction logic

---

BitFaster.Caching.UnitTests/Lru/ConcurrentTLruTests.cs

TLru tests on MacOS are less table - increase delay on that platform.

macos time

---

BitFaster.Caching.ThroughputAnalysis/Program.cs
BitFaster.Caching.UnitTests/Buffers/MpmcBoundedBufferTests.cs
BitFaster.Caching.UnitTests/Buffers/MpscBoundedBufferTests.cs
BitFaster.Caching.UnitTests/Buffers/StripedMpscBufferTests.cs
BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuTests.cs
BitFaster.Caching.UnitTests/Threaded.cs
BitFaster.Caching/Buffers/MpmcBoundedBuffer.cs
BitFaster.Caching/Buffers/MpscBoundedBuffer.cs
BitFaster.Caching/Buffers/PaddedHeadAndTail.cs
BitFaster.Caching/Buffers/StripedMpmcBuffer.cs
BitFaster.Caching/Buffers/StripedMpscBuffer.cs
BitFaster.Caching/Lfu/ConcurrentLfu.cs
BitFaster.Caching/Scheduler/BackgroundThreadScheduler.cs

A simplified multiple producer single consumer buffer, and striped version based on Caffeine BoundedBuffer. The drain to array method is more efficient. Latency is better for both background and foreground.
https://github.com/bitfaster/BitFaster.Caching/pull/197/commits/e34a2696b06e4c678c9ef787b75648e06e2e31ec - not sure how representative this run is - due to variability, it did _a lot_ of reps on ConcurrentLfuBackground on .NET6.
|                  Method |            Runtime |      Mean |     Error |    StdDev | Ratio | Allocated |
|------------------------ |------------------- |----------:|----------:|----------:|------:|----------:|
|    ConcurrentDictionary |           .NET 6.0 |  7.745 ns | 0.0335 ns | 0.0313 ns |  1.00 |         - |
| ConcurrentLfuBackground |           .NET 6.0 | …

mpsc buffer

---

BitFaster.Caching/Lfu/ConcurrentLfu.cs

When the write buffer is full or contended beyond number of retries, maintenance is run as part of the write. However, the written node was dropped.
This is causing test instability where sometimes written items are not present.

don't drop writes

---

BitFaster.Caching/Buffers/MpmcBoundedBuffer.cs
BitFaster.Caching/Buffers/MpscBoundedBuffer.cs
BitFaster.Caching/Buffers/PaddedHeadAndTail.cs

Mpsc buffer is unstable - many random test failures in previously stable tests. TryTake had a bug - not totally sure how the test could have passed previously
Go back to volatile static methods with full fence.
|                  Method |            Runtime |      Mean |     Error |    StdDev | Ratio | Allocated |
|------------------------ |------------------- |----------:|----------:|----------:|------:|----------:|
|    ConcurrentDictionary |           .NET 6.0 |  7.824 ns | 0.1213 ns | 0.1075 ns |  1.00 |         - |
| ConcurrentLfuBackground |           .NET 6.0 | 36.620 ns | 1.0541 ns | 3.0750 ns |  4.50 |         - |
|  ConcurrentLfuForeround |           .NET 6.0 | 68.245 ns | 1.2233 ns | 1.1443 ns |  8.72 |         - |
| ConcurrentLfuThreadPool |           .NET 6.0 | 72.527 ns | …

Volatile.Read/Write

---

BitFaster.Caching.UnitTests/Scheduler/BackgroundSchedulerTests.cs

Instability in BackgroundThreadScheduler WhenDisposedRunsToCompletion.
Try increasing timeout to 5 secs.

extend timeout

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuBuilderTests.cs
BitFaster.Caching/Lfu/Builder/AsyncConcurrentLfuBuilder.cs
BitFaster.Caching/Lfu/Builder/AtomicAsyncConcurrentLfuBuilder.cs
BitFaster.Caching/Lfu/Builder/AtomicConcurrentLfuBuilder.cs
BitFaster.Caching/Lfu/ConcurrentLfuBuilder.cs
BitFaster.Caching/Lfu/ConcurrentLfuBuilderExtensions.cs

Add:
- AsAsync
- WithAtomicGetOrAdd
- Compose both of the above
```cs
IAsyncCache<int, int> lru = new ConcurrentLfuBuilder<int, int>()
.WithAtomicGetOrAdd()
.AsAsyncCache()
.WithCapacity(3)
.Build();
```

ConcurrentLfuBuilder

---

BitFaster.Caching/Lru/ConcurrentLruCore.cs
BitFaster.Caching/Lru/PaddedQueueCount.cs
BitFaster.Caching/Padding.cs

|                   Method |            Runtime |       Mean |     Error |    StdDev | Ratio | Code Size | Allocated |
|------------------------- |------------------- |-----------:|----------:|----------:|------:|----------:|----------:|
|     ConcurrentDictionary |           .NET 6.0 |   7.764 ns | 0.0867 ns | 0.0768 ns |  1.00 |   1,523 B |         - |
|        FastConcurrentLru |           .NET 6.0 |   9.684 ns | 0.1058 ns | 0.0938 ns |  1.25 |   2,363 B |         - |
|            ConcurrentLru |           .NET 6.0 |  13.738 ns | 0.1324 ns | 0.1174 ns |  1.77 |   2,395 B |         - |
|            AtomicFastLru |           .NET 6.0 |  20.212 ns | 0.1765 ns | 0.1651 ns |  2.60 |     846 B |         - |
|       FastConcurrentTLru |           .NET 6.0 |  26.661 ns | 0.2663 ns | 0.2223 ns …

pad counters

---

BitFaster.Caching/Lru/ConcurrentLruCore.cs

Improve correctness for ConcurrentLru: use the result of interlocked inc/dec and volatile reads for counter values. This eliminates races when propagating items across queues. Read/write throughput and LruCycleBench latency are unchanged.

correctness

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuTests.cs
BitFaster.Caching.UnitTests/Threaded.cs
BitFaster.Caching/Lfu/ConcurrentLfu.cs

In the Read+Write scenario, the bottleneck is lock contention while attempting to enter the maintenance lock.
Breakdown of time in maintenance:
Fix:
1. Try to exit the lock early if maintenance has just run and it is possible to add to the write buffer. This reduces wait time for a queue of writes when in a lock convoy.
2. When maintenance is running on the background thread, keep track of whether the write buffer was fully drained, and if not run maintenance again. This has the effect of maintenance constantly running in the background when the buffers are populated. 
3. Remove the spin wait, which is just slowing things down (throughput is measurably lower).
This is an approx 10% throughput gain for the Read+Write scenario.

lock contention

---

.github/workflows/codeql-analysis.yml
BitFaster.Caching/BitFaster.Caching.csproj
BitFaster.Caching/ReadMe.md

Switch CodeQL to run on windows since it fails to package the readme file on ubuntu for some reason.
```
Running dotnet build --no-incremental /p:UseSharedCompilation=false /home/runner/work/BitFaster.Caching/BitFaster.Caching/BitFaster.sln
MSBuild version 17.3.0+92e077650 for .NET
Determining projects to restore...
All projects are up-to-date for restore.
BitFaster.Caching -> /home/runner/work/BitFaster.Caching/BitFaster.Caching/BitFaster.Caching/bin/Debug/netstandard2.0/BitFaster.Caching.dll
BitFaster.Caching -> /home/runner/work/BitFaster.Caching/BitFaster.Caching/BitFaster.Caching/bin/Debug/netcoreapp3.1/BitFaster.Caching.dll
BitFaster.Caching -> /home/runner/work/BitFaster.Caching/BitFaster.Caching/BitFaster.Caching/bin/Debug/net6.0/BitFaster.Caching.dll
BitFaster.Caching.UnitTests …
```

package readme

---

BitFaster.Caching.ThroughputAnalysis/Mode.cs
BitFaster.Caching/Atomic/AtomicFactoryAsyncCache.cs
BitFaster.Caching/Atomic/AtomicFactoryCache.cs
BitFaster.Caching/Atomic/AtomicFactoryScopedAsyncCache.cs
BitFaster.Caching/Atomic/AtomicFactoryScopedCache.cs
BitFaster.Caching/Buffers/MpmcBoundedBuffer.cs
BitFaster.Caching/Buffers/MpscBoundedBuffer.cs
BitFaster.Caching/Ex.cs
BitFaster.Caching/Lfu/ConcurrentLfu.cs
BitFaster.Caching/Lfu/LfuCapacityPartition.cs
BitFaster.Caching/Lfu/LfuNodeList.cs
BitFaster.Caching/Lru/CapacityPartitionExtensions.cs
BitFaster.Caching/Lru/ClassicLru.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs
BitFaster.Caching/Lru/EqualCapacityPartition.cs
BitFaster.Caching/Lru/FavorWarmPartition.cs
BitFaster.Caching/Lru/LruDebugView.cs
BitFaster.Caching/Scoped.cs
BitFaster.Caching/ScopedAsyncCache.cs
BitFaster.Caching/ScopedCache.cs

Implement a throw helper using the pattern used in the base library, e.g. https://github.com/stephentoub/corefx/blob/master/src/System.Linq/src/System/Linq/ThrowHelper.cs
This has a measurable benefit for DrainStatus.ShouldDrain(). [This article](https://dunnhq.com/posts/2022/throw-helper/) gives more details explaining why.
Before:
|                  Method |            Runtime |      Mean |     Error |    StdDev | Ratio | Allocated |
|------------------------ |------------------- |----------:|----------:|----------:|------:|----------:|
| ConcurrentLfuBackground |           .NET 6.0 | 36.620 ns | 1.0541 ns | 3.0750 ns |  4.50 |         - |
After:
|                  Method |            Runtime |      Mean |     Error |    StdDev | Ratio | Allocated |
|------------------------ …

throwhelper

---

BitFaster.Caching.UnitTests/Lfu/CmSketchTests.cs
BitFaster.Caching/Lfu/CmSketch.cs

Fix logic to detect whether the table was incremented.
| Method |     Mean |    Error |   StdDev | Ratio | Allocated |
|------- |---------:|---------:|---------:|------:|----------:|
|    Inc | 21.80 us | 0.085 us | 0.071 us |  1.00 |         - |
| IncAvx | 14.64 us | 0.032 us | 0.029 us |  0.67 |         - |
This is actually now faster because reset is called fewer times.

fix AVX reset

---

BitFaster.Caching.HitRateAnalysis/Arc/RunnerConfig.cs
BitFaster.Caching.HitRateAnalysis/Wikibench/Runner.cs
BitFaster.Caching.HitRateAnalysis/Zipfian/Runner.cs
BitFaster.Caching.ThroughputAnalysis/BitFaster.Caching.ThroughputAnalysis.csproj
BitFaster.Caching.ThroughputAnalysis/CommandParser.cs
BitFaster.Caching.ThroughputAnalysis/ConfigFactory.cs
BitFaster.Caching.ThroughputAnalysis/Exporter.cs
BitFaster.Caching.ThroughputAnalysis/Program.cs
BitFaster.Caching.ThroughputAnalysis/Runner.cs
BitFaster.Caching.ThroughputAnalysis/SizeExec.bat
BitFaster.Caching.ThroughputAnalysis/ThroughputBenchConfig.cs
BitFaster.Caching.ThroughputAnalysis/ThroughputBenchmark.cs
BitFaster.Caching.UnitTests/Counters/StripedLongAdderTests.cs
BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuTests.cs
BitFaster.Caching.UnitTests/SingletonCacheTests.cs

Enable running with multiple sizes via a batch script.

parameterize throughput tests

---

BitFaster.Caching.ThroughputAnalysis/ConfigFactory.cs
BitFaster.Caching.ThroughputAnalysis/ThroughputBenchmark.cs

For eviction, fully prime the cache with unique values that will not be fetched as part of the test run.

warmup eviction scenario

---

BitFaster.Caching.Benchmarks/Lfu/Reset.cs
BitFaster.Caching.Benchmarks/Lfu/SketchReset.cs
BitFaster.Caching/Lfu/CmSketch.cs

Unroll the reset loop to improve throughput. Not earth shattering, but worth almost 1 ms for a 1 million element table.
| Method |    Size |             Mean |          Error |         StdDev | Ratio |
|------- |-------- |-----------------:|---------------:|---------------:|------:|
| Reset1 |       4 |         8.893 ns |      0.0390 ns |      0.0304 ns |  1.00 |
| Reset2 |       4 |         6.170 ns |      0.0873 ns |      0.0816 ns |  0.70 |
| Reset4 |       4 |         5.883 ns |      0.0722 ns |      0.0675 ns |  0.66 |
|        |         |                  |                |                |       |
| Reset1 |     128 |       282.571 ns |      2.4478 ns |      2.2896 ns |  1.00 |
| Reset2 |     128 |       176.850 ns |      0.7743 ns |      0.6045 ns |  0.63 |
| Reset4 |     128 | …

optimize sketch reset

---

BitFaster.Caching.ThroughputAnalysis/MemoryCacheAdaptor.cs

Fails with null ref when running the eviction test.

fix mem cache

---

BitFaster.Caching.HitRateAnalysis/BitFaster.Caching.HitRateAnalysis.csproj
BitFaster.Caching.HitRateAnalysis/Zipfian/Runner.cs
BitFaster.Caching.ThroughputAnalysis/FastZipf.cs
BitFaster.Caching.ThroughputAnalysis/Program.cs
BitFaster.Caching.ThroughputAnalysis/ThroughputBenchConfig.cs

This is about 20x faster than using Math.Numerics, since the harmonic is computed once and the loop that generates the values is now parallelized. 
Only the random generation is serial - this means that the output is identical Math.Numerics since the same 'random' numbers are generated.

faster zipf

---

BitFaster.Caching.HitRateAnalysis/Analysis.cs
BitFaster.Caching.HitRateAnalysis/BitFaster.Caching.HitRateAnalysis.csproj
BitFaster.Caching.HitRateAnalysis/MemoryCacheAdaptor.cs
BitFaster.Caching.HitRateAnalysis/Zipfian/Runner.cs

Add an adaptor with a simple counter for metrics and plumb into tests.

include memcache in hit rate analysis

---

BitFaster.Caching/Lru/ConcurrentLruCore.cs

Increase the number of LRU cycle attempts to 5. This prevents runaway growth when stress tested on an AMD 5800X CPU.

max attempts = 5

---

.github/workflows/gate.yml
.github/workflows/mac-gate.yml

Generate a test report via https://github.com/phoenix-actions/test-reporting

test report

---

BitFaster.Caching/Lfu/CmSketch.cs

I had missed a couple of `Vector128<int>.Zero` cases, and there was also a call site where it is possible to use `AllBitsSet`.
Considered swapping to 
```cs
bool wasInc = !Avx2.TestZ(result, result);
```
Avx2.TestZ is [_mm256_testz_si256/VPTEST](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/intrinsics/intrinsics-for-intel-advanced-vector-extensions/intrinsics-for-packed-test-operations/mm256-testz-si256.html).
Avx2.MoveMask is [_mm256_movemask_epi8/VPMOVMSKB](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/intrinsics/intrinsics-for-avx2/intrinsics-for-miscellaneous-operations-2/mm256-movemask-epi8.html).
According to …

zero again

---

BitFaster.Caching/Atomic/AtomicFactoryAsyncCache.cs
BitFaster.Caching/Atomic/AtomicFactoryCache.cs
BitFaster.Caching/Atomic/AtomicFactoryScopedAsyncCache.cs
BitFaster.Caching/Atomic/AtomicFactoryScopedCache.cs
BitFaster.Caching/CacheDebugView.cs
BitFaster.Caching/Lru/ConcurrentLru.cs
BitFaster.Caching/Lru/ConcurrentTLru.cs
BitFaster.Caching/Lru/FastConcurrentLru.cs
BitFaster.Caching/Lru/FastConcurrentTLru.cs
BitFaster.Caching/ScopedAsyncCache.cs
BitFaster.Caching/ScopedAsyncCacheDebugView.cs
BitFaster.Caching/ScopedCache.cs
BitFaster.Caching/ScopedCacheDebugView.cs

Implement debug view for all cache variants.

Consistent debug view

---

BitFaster.Caching.Benchmarks/BitFaster.Caching.Benchmarks.csproj
BitFaster.Caching.Benchmarks/Lru/TLruTimeBenchmark.cs
BitFaster.Caching.Benchmarks/TimeBenchmarks.cs
BitFaster.Caching.UnitTests/Lru/TLruTickCount64PolicyTests .cs
BitFaster.Caching.UnitTests/Lru/TlruStopwatchPolicyTests.cs
BitFaster.Caching/Lru/ConcurrentTLru.cs
BitFaster.Caching/Lru/FastConcurrentTLru.cs
BitFaster.Caching/Lru/TlruStopwatchPolicy.cs
BitFaster.Caching/Lru/TlruTickCount64Policy.cs

Environment.TickCount64 was introduced in .NET Core. Use this as the default time policy on .NET Core3+ to reduce lookup latency for TLRU. This has the effect of reducing time resolution from ~1us to 10-16ms, but is substantially faster. Expiring items faster than 10ms is not a likely use case, so this is a good trade off.
TickCount64 takes 292,277,266 years to wrap around, so for practical purposes we assume it will never wrap.
|                 Method |      Mean |     Error |    StdDev | Ratio |
|----------------------- |----------:|----------:|----------:|------:|
|         DateTimeUtcNow | 25.411 ns | 0.2257 ns | 0.1885 ns |  1.00 |
|   EnvironmentTickCount |  1.830 ns | 0.0676 ns | 0.1270 ns |  0.07 |
| EnvironmentTickCount64 |  1.843 ns | 0.0683 ns | 0.1122 ns |  0.07 |
| …

Use Environment.TickCount64 for TLRU on .NET6

---

BitFaster.Caching.UnitTests/Lru/ConcurrentLruBuilderTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentTLruTests.cs
BitFaster.Caching/Lru/Builder/LruBuilderBase.cs
BitFaster.Caching/Lru/Builder/LruInfo.cs
BitFaster.Caching/Lru/ConcurrentLruBuilder.cs

Enable auto fallback to high resolution clock on .NET core, enabling use of the previous higher precision expiry when time to live is low enough (2x clock resolution). 
Ensure unit tests cover both variants of TLRU.

auto detect high res clock

---

BitFaster.Caching.UnitTests/Lru/TLruTickCount64PolicyTests .cs
BitFaster.Caching/Lru/TlruTickCount64Policy.cs

- Not all code paths use Environment.TickCount64
- Guard against setting invalid time to live

TLruTickCount64Policy uses 64 bit time

---

BitFaster.Caching.UnitTests/Lru/TLruTickCount64PolicyTests .cs
BitFaster.Caching.UnitTests/Lru/TlruStopwatchPolicyTests.cs
BitFaster.Caching/Lru/TlruStopwatchPolicy.cs
BitFaster.Caching/Lru/TlruTickCount64Policy.cs

Setting TlruStopwatchPolicy TTL to TimeSpan.MaxValue results in a negative TTL, silently putting TLRU into an invalid state. This is because multiplying long.MaxValue by 1.0d results in silent overflow (1 is the stopwatch adjustment factor on my machine).
Instead, take the maximum possible TTL across platforms (Mac has highest stopwatch adjustment factor, and therefore lowest TTL), and throw if user attempts to set a TTL higher than this. Since this value is much lower than long.MaxValue, we also avoid overflow. For reference, the max is a little less than 106,751 days, or about 292 years.
With this approach, the user will get the same behavior on all platforms. Either you can set the TTL, or it will throw.

Setting stopwatch policy TTL to TimeSpan.MaxValue gives invalid TTL

---

.github/workflows/gate.yml
BitFaster.Caching.UnitTests/BitFaster.Caching.UnitTests.csproj
BitFaster.Caching.UnitTests/Intrinsics.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentTLruTests.cs
BitFaster.Caching.UnitTests/Lru/FastConcurrentTLruTests.cs
BitFaster.Caching.UnitTests/Lru/TLruTickCount64PolicyTests .cs
BitFaster.Caching.UnitTests/Scheduler/BackgroundSchedulerTests.cs
BitFaster.Caching.UnitTests/Scheduler/ThreadPoolSchedulerTests.cs
BitFaster.Caching.UnitTests/TimeSpanExtensions.cs

This PR:
1. Enables unit tests to build and run on .NET 4.8, .NET Core 3.1 and .NET 6 targets.
2. Runs all targets on windows
3. Runs .NET6 on mac
4. Collects code coverage for 3.1 and 6.0, since .NET Framework is not well supported in dotnet test.

multi-target unit tests

---

BitFaster.Caching.Benchmarks/Lru/TLruTimeBenchmark.cs
BitFaster.Caching.UnitTests/Atomic/AtomicFactoryAsyncCacheTests.cs
BitFaster.Caching.UnitTests/Atomic/AtomicFactoryCacheTests.cs
BitFaster.Caching.UnitTests/CacheEventProxyBaseTests.cs
BitFaster.Caching.UnitTests/CacheEventsTests.cs
BitFaster.Caching.UnitTests/CacheMetricsTests.cs
BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuTests.cs
BitFaster.Caching.UnitTests/Lru/ClassicLruTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruBuilderTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentTLruTests.cs
BitFaster.Caching.UnitTests/Lru/TLruTickCount64PolicyTests .cs
BitFaster.Caching.UnitTests/Lru/TelemetryPolicyTests.cs
BitFaster.Caching.UnitTests/Lru/TlruStopwatchPolicyTests.cs
BitFaster.Caching.UnitTests/ScopedAsyncCacheTestBase.cs
BitFaster.Caching.UnitTests/ScopedCacheTestBase.cs
BitFaster.Caching/BitFaster.Caching.csproj
BitFaster.Caching/CacheEventProxyBase.cs
BitFaster.Caching/ICacheEvents.cs
BitFaster.Caching/ICacheMetrics.cs
BitFaster.Caching/Lru/Builder/LruBuilderBase.cs
BitFaster.Caching/Lru/Builder/LruInfo.cs
BitFaster.Caching/Lru/ConcurrentLruBuilder.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs
BitFaster.Caching/Lru/ConcurrentTLru.cs
BitFaster.Caching/Lru/FastConcurrentTLru.cs
BitFaster.Caching/Lru/ITelemetryPolicy.cs
BitFaster.Caching/Lru/StopwatchTickConverter.cs
BitFaster.Caching/Lru/TLruLongTicksPolicy.cs
BitFaster.Caching/Lru/TlruTickCount64Policy.cs

Package validation reveals a number of breaking changes since v2.0.0. Use v2.0.0 as the baseline since NServiceBus.RabbitMQ 8.0.2 is built against 2.0.0 and has reference constraint of [2.0.0 - 3.0.0]. Therefore, changes could break any consumer of NServiceBus who attempted to update to the latest version of BitFaster.Caching in their application.
Summary of changes:
- Reverted change to use different TLRU time policies. Now .NET standard uses the stopwatch based policy, and .NET3.1 and .NET6 use Environment.TickCount64 based policy. This is implemented as 2 classes that have the same name, with #ifdef compilation to select as appropriate.
- New interface members are now only provided on .NET3.1 and .NET6, with default no-op implementations.
- This removes `ICacheEvents.ItemUpdated` for …

Fix back compat issues against v2.0.0

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching.UnitTests/Lru/ValueFactory.cs
BitFaster.Caching/Lfu/ConcurrentLfu.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs

Address https://github.com/bitfaster/BitFaster.Caching/issues/311: provide an overload that allows passing args into the factory method to avoid closure allocs. This PR so far only addresses the basic support for LRU/LFU instance methods.
To support across the board (builder support, ICache etc.) is a breaking change, and requires further changes to Atomic/Scoped etc.
Some variation on GetOrAdd, but seems to be noise not regression.
|                   Method |            Runtime |       Mean | Ratio | Code Size | Allocated |
|------------------------- |------------------- |-----------:|------:|----------:|----------:|
|     ConcurrentDictionary |           .NET 6.0 |   7.156 ns |  1.00 |   1,523 B |         - |
|        FastConcurrentLru |           .NET 6.0 |  10.178 ns |  1.42 | …

factory delegate has arg to avoid closure allocs

---

BitFaster.Caching.UnitTests/Lru/ClassicLruTests.cs
BitFaster.Caching/Lru/ClassicLru.cs

To add the method `V GetOrAdd<TArg>(K key, Func<K, TArg, V> valueFactory, TArg factoryArgument)` to `ICache`, all implementations must have this method. Implement for `ClassicLru`.

ClassicLru supports value factory arg

---

BitFaster.Caching.UnitTests/Atomic/AtomicFactoryScopedAsyncCacheTests.cs
BitFaster.Caching.UnitTests/Atomic/AtomicFactoryScopedCacheTests.cs
BitFaster.Caching.UnitTests/CacheTests.cs
BitFaster.Caching.UnitTests/ScopedAsyncCacheTestBase.cs
BitFaster.Caching.UnitTests/ScopedAsyncCacheTests.cs
BitFaster.Caching.UnitTests/ScopedCacheTestBase.cs
BitFaster.Caching/IAsyncCache.cs
BitFaster.Caching/ICache.cs
BitFaster.Caching/IScopedAsyncCache.cs
BitFaster.Caching/IScopedCache.cs
BitFaster.Caching/ScopedAsyncCache.cs
BitFaster.Caching/ScopedCache.cs

Add support for factory methods that take an argument to `ICache`, `IAsyncCache`, `IScopedCache` and `IAsyncScopedCache`.
ScopedAsyncCache does have a partial dupe method - this is a similar situation to [ConcurrentDictionary.GetOrAdd](https://source.dot.net/#System.Collections.Concurrent/System/Collections/Concurrent/ConcurrentDictionary.cs,1162) which has dupe code for each method overload in .NET framework.

Cache interface support for factory arg

---

.github/workflows/gate.yml

The set-output command is deprecated and will be disabled soon. See:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This is caused by the test reporting: update it.

update test reporting

---

BitFaster.Caching.HitRateAnalysis/Zipfian/Runner.cs
BitFaster.Caching.ThroughputAnalysis/BitFaster.Caching.ThroughputAnalysis.csproj
BitFaster.Caching.ThroughputAnalysis/CacheFactory.cs
BitFaster.Caching.ThroughputAnalysis/ConfigFactory.cs
BitFaster.Caching.ThroughputAnalysis/FastZipf.cs
BitFaster.Caching.ThroughputAnalysis/Program.cs
BitFaster.Caching.ThroughputAnalysis/Runner.cs
BitFaster.Caching.ThroughputAnalysis/ThroughputBenchConfig.cs
BitFaster.Caching.ThroughputAnalysis/ThroughputBenchmark.cs

With the original method when n == 100_000_000 my machine can compute about 250 zipf samples per second, so it would take about 4.6 days to compute all samples. The old method is n^2 complexity, so its very slow for large n.
Switched to this method:
https://jasoncrease.medium.com/zipf-54912d5651cc
Now 100_000_000 samples takes about 10-25 seconds running on a single thread. The output distribution is not identical so previous throughput results are not directly comparable: throughput measurements are about 5% lower, but have the same relative ranking.
Additional changes:
- Cache key is now long, since new code generates long values.
- Fixed various build warnings.

even faster zipf

---

BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs

Fix cycle logic so that if all items are touched when a new item is added (thus the coldest is cycled back into warm) we simply discard the coldest cache item (last item in cold queue).

remove coldest when full

---

BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching.UnitTests/Threaded.cs

After updating the visual studio test runner package, code coverage has dropped. Try adding tests to cover race condition guard code that is hard to reach. 
These are now soak tests where we verify integrity at the end - should they be in a different file/different name?

soak tests to increase code coverage

---

BitFaster.Caching/Throw.cs

Use `[DoesNotReturn]` for throw helper methods.

doesnotreturn

---

BitFaster.Caching/Atomic/AtomicFactoryAsyncCache.cs
BitFaster.Caching/Atomic/AtomicFactoryCache.cs
BitFaster.Caching/Atomic/AtomicFactoryScopedAsyncCache.cs
BitFaster.Caching/Atomic/AtomicFactoryScopedCache.cs
BitFaster.Caching/Buffers/MpmcBoundedBuffer.cs
BitFaster.Caching/Buffers/MpscBoundedBuffer.cs
BitFaster.Caching/CacheDebugView.cs
BitFaster.Caching/Lfu/LfuCapacityPartition.cs
BitFaster.Caching/Lfu/LfuNodeList.cs
BitFaster.Caching/Lru/CapacityPartitionExtensions.cs
BitFaster.Caching/Lru/ClassicLru.cs
BitFaster.Caching/Lru/ConcurrentLruBuilder.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs
BitFaster.Caching/Lru/EqualCapacityPartition.cs
BitFaster.Caching/Lru/FavorWarmPartition.cs
BitFaster.Caching/Lru/StopwatchTickConverter.cs
BitFaster.Caching/Lru/TlruTickCount64Policy.cs
BitFaster.Caching/Scoped.cs
BitFaster.Caching/ScopedAsyncCache.cs
BitFaster.Caching/ScopedAsyncCacheDebugView.cs
BitFaster.Caching/ScopedCache.cs
BitFaster.Caching/ScopedCacheDebugView.cs

Removing braces around `if(...) { throw; }` to eliminate the uncovered code:
There is a change to coverlet that states decorating the throw helper methods with `[DoesNotReturn]` should eliminate this (imlpemented in https://github.com/bitfaster/BitFaster.Caching/pull/386), but it doesn't work. Therefore, simply remove the braces to avoid artificially counting code coverage lower.

rem braces

---

BitFaster.Caching.UnitTests/Atomic/AtomicFactoryCacheTests.cs
BitFaster.Caching.UnitTests/Atomic/AtomicFactoryTests.cs
BitFaster.Caching.UnitTests/CacheTests.cs
BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuTests.cs
BitFaster.Caching.UnitTests/Lru/ClassicLruTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching/Atomic/AtomicFactory.cs
BitFaster.Caching/Atomic/AtomicFactoryCache.cs
BitFaster.Caching/ICache.cs
BitFaster.Caching/Lfu/ConcurrentLfu.cs
BitFaster.Caching/Lru/ClassicLru.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs

Provide functional parity with `ConcurrentDictionary` for `ICache.TryRemove`.
- Provide `bool TryRemove(K key, out V value)` and `bool TryRemove(KeyValuePair<K,V> item)`
- Underneath, use `ConcurrentDictionary TryRemove(key, out value)` for `ICache TryRemove(K key)` and `TryRemove(K key, out V value)` to avoid double dictionary lookup then remove.
- Use the old method of retrieve, check, then atomic delete for `TryRemove(KeyValuePair<K,V>)`
- `ICache` default implementations for backwards compatibility throw `NotSupportedException`. There is no way to correctly implement either new method, so it is better to throw than give the caller an incorrect result. This would only apply if a caller implements ICache themselves, upgrades the library, and doesn't have impls for these methods.
- …

Align ICache.TryRemove overloads with ConcurrentDictionary

---

BitFaster.Caching.UnitTests/Scheduler/BackgroundSchedulerTests.cs

This causes static analysis to fail when upgrading xunit packages.

replace tcs blocking task method call

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuTests.cs
BitFaster.Caching/Lfu/ConcurrentLfu.cs

Calling `Clear()` with `BackgroundThreadScheduler` can result in a situation where window/probation/protected contains an item that was already removed. Since the clear logic trims n items, where n == cache.Count, the already removed items pollute the list of candidates resulting in non-removed items remaining in the cache.

ConcurrentLfu.Clear() polluted by removed items

---

BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs

When ConcurrentLru is cleared, the isWarm flag was not reset. Consequently, items cannot enter the warm queue until they are requested a second time. This is confusing, because the cache behaves differently after it is cleared, and reduces effective capacity after clear reducing hit rate.

Reset isWarm when clearing ConcurrentLru

---

BitFaster.Caching.UnitTests/ReferenceCountTests.cs
BitFaster.Caching.UnitTests/ScopedCacheTests.cs
BitFaster.Caching.UnitTests/ScopedTests.cs
BitFaster.Caching/ReferenceCount.cs
BitFaster.Caching/Scoped.cs
BitFaster.Caching/ScopedCacheDefaults.cs
BitFaster.Caching/Throw.cs

See the [wikipedia description for the ABA problem](https://en.wikipedia.org/wiki/ABA_problem).
At some point, ReferenceCount was updated to implement IEquatable (possibly because code analysis said this is a good idea). This changed `operator ==` from the default which tests whether two references of that type refer to the same object, to comparing for field equality. 
This broke the `Scoped` class. Specifically, [this line](https://github.com/bitfaster/BitFaster.Caching/blob/5ffc05a6317ad1af4874d59ad8a45c381b0c0f02/BitFaster.Caching/Scoped.cs#L54) and [this line](https://github.com/bitfaster/BitFaster.Caching/blob/5ffc05a6317ad1af4874d59ad8a45c381b0c0f02/BitFaster.Caching/Scoped.cs#L83) are now susceptible to the ABA problem because the equality operator is checking field values:
`if …

Scoped cache broken due to operator== ABA problem

---

BitFaster.Caching.UnitTests/Buffers/MpscBoundedBufferTests.cs
BitFaster.Caching.UnitTests/TaskExtensions.cs
BitFaster.Caching/Buffers/MpscBoundedBuffer.cs

It seems like the core problem is that xunit will start to heavily parallelize test execution, and the github action runs on a 2 core machine. Previous bug fix PR added two more soak tests, which led to more severe thread starvation. Increasing the timeout makes this much more stable. Next step will be to break out soak tests and [not run them in parallel](https://xunit.net/docs/running-tests-in-parallel).
- Removed use of `[Fact(Timeout=x]` because it is documented as undefined behavior when tests are run in parallel
- Added `Task.TimeoutAfter` extension method. This is likely not better, because the real issue is xunit scheduling too many threads.
- Cleaned up using statement/redundant cast in `MpscBoundedBuffer`

Extend timeout for mpsc buffer test

---

BitFaster.Caching.UnitTests/Lru/ConcurrentLruSoakTests.cs

There is a very rare race that can lead to one extra item being evicted. Until this is fixed, update the test expectation to avoid instability.
```
Failed BitFaster.Caching.UnitTests.Lru.ConcurrentLruTests.WhenSoakConcurrentGetCacheEndsInConsistentState [4 s]
Error Message:
Expected lru.Count to be within 1u from 9, but found 7.
```

update soak bounds

---

BitFaster.Caching.UnitTests/Lru/ConcurrentTLruTests.cs

Items get removed due to exceeding TTL, causing test to fail. Set a higher TTL to avoid this (event test is not intended to verify time based expiry fires the event).

increase ttl

---

BitFaster.Caching.UnitTests/Atomic/AtomicFactorySoakTests.cs
BitFaster.Caching/Atomic/AtomicFactory.cs

Soak test for AtomicFactory fails intermittently:
```
[xUnit.net 00:00:59.66]     AtomicFactorySoakTests.WhenGetOrAddIsConcurrentValuesCreatedAtomically [FAIL]
Failed Atomic.AtomicFactorySoakTests.WhenGetOrAddIsConcurrentValuesCreatedAtomically [26 ms]
Error Message:
Expected counters.Sum(x => x) to be 1024, but found 1071 (difference of 47).
```
This is due to items being evicted by `ConcurrentLru` (which is not expected given that item count falls within capacity). Switch to a pre-allocated `ConcurrentDictionary`, and investigate the warmup bug separately.
Also moved the volatile read in the AtomicFactory code.

fix atomic factory soak test

---

BitFaster.Caching.UnitTests/HashTablePrimesTests.cs
BitFaster.Caching/HashTablePrimes.cs
BitFaster.Caching/Lfu/ConcurrentLfu.cs
BitFaster.Caching/Lru/ClassicLru.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs

Today, the capacity passed into the cache ctor is used to initialize the `ConcurrentDictionary`. This has 2 problems:
1. By allocating up front, we eliminate resizing. However, if the capacity is very large and the cache is not used, we will waste a lot of memory.
2. On earlier versions of .NET, `ConcurrentDictionary` uses the capacity arg to directly initialize the hash table size (as noted [here](https://stackoverflow.com/questions/60005428/concurrentdictionary-proper-small-initial-capacity)). On resize, the hashtable is grown to [2x + 1 while avoiding factors of 3, 5, or 7 (but not larger)](https://github.com/microsoft/referencesource/blob/master/mscorlib/system/collections/Concurrent/ConcurrentDictionary.cs). On newer versions of .NET, both initial size and resize is based the next …

Use prime for ConcurrentDictionary initial size

---

BitFaster.Caching.UnitTests/Buffers/MpmcBoundedBufferSoakTests.cs
BitFaster.Caching.UnitTests/Buffers/MpscBoundedBufferSoakTests.cs
BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuTests.cs
BitFaster.Caching.UnitTests/RepeatAttribute.cs

Coverage of some cases is intermittent. Repeat soak tests to ensure coverage.
Repeat attribute taken from https://stackoverflow.com/questions/31873778/xunit-test-fact-multiple-times.

repeat tests to stabilize coverage

---

BitFaster.Caching/Atomic/AsyncAtomicFactory.cs
BitFaster.Caching/Atomic/AtomicFactory.cs
BitFaster.Caching/Atomic/ScopedAsyncAtomicFactory.cs
BitFaster.Caching/Atomic/ScopedAtomicFactory.cs

- Remove redundant use of Volatile.Read/Write inside lock statements. The lock inserts a memory barrier/full fence on entry and exit, so half fences are redundant.
- Use Volatile.Read/Write consistently for checking initializer classes.
- Initializer classes lock `this` instead of allocating an additional lock object. In general, this is a bad practice, but the initializer is a private class so it cannot be locked outside the control of the enclosing class.

consistent use of volatile/lock

---

BitFaster.Caching/AssemblyInfo.cs

[SkipLocalsInit] can be used to improve performance - https://github.com/dotnet/roslyn/blob/master/docs/features/skiplocalsinit.md
Runtime applies this attribute on all their assemblies for 5.0 - https://github.com/dotnet/runtime/search?q=SkipLocalsInit

Enable SkipLocalsInit for .NET6

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuSoakTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching/Lfu/ConcurrentLfu.cs

This test exposed a bug - there was logic missing to handle nodes being removed while being read/updated.
In this case, the node was previously in probation, so Position=Probation, and the node's list is null (since it was removed). The debug assert attempts to verify that the probation node is attached to the list, which it is not.
```
Error Message:
System.InvalidOperationException : Node is already attached to a different list.
Stack Trace:
at BitFaster.Caching.Throw.InvalidOp(String message) in /_/BitFaster.Caching/Throw.cs:line 29
at BitFaster.Caching.Lfu.LfuNodeList`2.ValidateNode(LfuNode`2 node) in /_/BitFaster.Caching/Lfu/LfuNodeList.cs:line 140
at BitFaster.Caching.Lfu.LfuNodeList`2.Remove(LfuNode`2 node) in /_/BitFaster.Caching/Lfu/LfuNodeList.cs:line 61
at …
```

soak lfu add + fix detached nodes

---

.editorconfig
BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuTests.cs
BitFaster.Caching/Atomic/AsyncAtomicFactory.cs
BitFaster.Caching/Atomic/AtomicFactory.cs
BitFaster.Caching/Atomic/AtomicFactoryScopedAsyncCache.cs
BitFaster.Caching/Atomic/AtomicFactoryScopedCache.cs
BitFaster.Caching/Atomic/ScopedAsyncAtomicFactory.cs
BitFaster.Caching/Atomic/ScopedAtomicFactory.cs
BitFaster.Caching/BitFaster.Caching.csproj
BitFaster.Caching/Lfu/CmSketchCore.cs
BitFaster.Caching/Lfu/LfuCapacityPartition.cs
BitFaster.Caching/Lru/ClassicLru.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs
BitFaster.Caching/Scheduler/BackgroundThreadScheduler.cs
BitFaster.Caching/Scheduler/ThreadPoolScheduler.cs
BitFaster.Caching/ScopedAsyncCache.cs
BitFaster.Caching/ScopedCache.cs

Enable:
- AnalysisModePerformance
- AnalysisModeDocumentation
- AnalysisModeInteroperability
- AnalysisModeReliability
Fix or suppress violations.

enable code analysis

---

BitFaster.Caching/Buffers/MpscBoundedBuffer.cs
BitFaster.Caching/Lfu/ConcurrentLfu.cs

Optimizations:
- Successive buffer reads/writes don't need two volatile ops. They can piggyback.
- Closely match Caffeine volatile operations with regard to drain status.
- Inline drain status
- Inline EvictIterator
This is definitely faster, but less stable during the benchmark run - fluctuating between 23 ns/op - 33 ns/op. Gain is most consistent on the evict throughput.

optimize LFU

---

BitFaster.Caching/Lru/ConcurrentLruCore.cs

- Simplify eviction logic: remove retry loop and simply discard the coldest item. Logic is now entirely based on the result of the preceding interlocked operation, so now there are no races.
- Inline helper methods
- Consolidate removal logic to always call into OnRemove
There is a marginal improvement in throughput for the eviction scenario for higher thread counts, likely because some volatile read calls have been eliminated.
MaxCycles = 3 was chosen because that is the threshold where the Arc OLTP scenario is closest to optimal. There is almost no difference in other scenarios.

Revise LRU eviction logic

---

BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentTLruTests.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs

During warmup, remove the volatile read to determine warm count, and instead move directly to warm and use the result of the interlocked increment. This eliminates any possible race in the transition between cold and warm.
The sequence of items in the underlying queues during cache warmup now changes: the first item added to the cache will be pushed to the cold queue. Previously it would stay in warm. Hence, some tests that depend on item order require updating.

Eliminate races during LRU warmup

---

BitFaster.Caching.UnitTests/Lru/ConcurrentLruSoakTests.cs

Previously, items were evicted as the item count approached capacity. This was not expected behavior, items should not be evicted until capacity is reached.
Eliminating the races during Cycle and Cycle warm have made this stable.

Verify LRU stability during warmup

---

BitFaster.Caching/Lru/ConcurrentLruCore.cs

This method is only invoked during cache warmup. Therefore, don't inline it.

Don't inline LRU warmup method 

---

BitFaster.Caching.HitRateAnalysis/Arc/Runner.cs

Running the hit rate analysis Arc OLTP scenario causes a machine with 32gb ram to run out of memory and grind to a halt.
Introduce a different run order for large cache sizes to mitigate this. Running in dotMemory shows that MemoryCache is allocating a crazy amount of ValueTuples
Rough breakdown:
Blue: MemoryCache ~8.2 gb
Green: ConcurrentLfu ~102 mb
Yellow: ConcurrentLru ~43 mb
Red: ClassicLru ~71mb
ConcurrentLfu is allocating an Action on each drain: this should be cached.

Fix HitRateAnalysis OOM

---

BitFaster.Caching/Lfu/ConcurrentLfu.cs

Calling drain buffers via the scheduler requires allocating an `Action`. This shows up when memory profiling the hit rate analysis test:
Cache the delegate to avoid this allocation. The correct approach would be for `IScheduler` to accept `Action<T>`, but that is a breaking change.

Cache LFU drain buffers delegate

---

BitFaster.Caching.UnitTests/Lru/FastConcurrentLruTests.cs
BitFaster.Caching.UnitTests/Lru/FastConcurrentTLruTests.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs

Even when the metrics and events are not defined, `ConcurrentLruCore` returns the internal proxy class through the optional properties. This makes it look like those features are enabled when they are not.
Fix this so that the optional.HasValue returns false when features are disabled.

LRU metrics and events should be optional

---

BitFaster.Caching/Lru/AfterReadStopwatchPolicy.cs
BitFaster.Caching/Lru/AfterReadTickCount64Policy.cs

This does not need to be part of the public API surface.

Mark AfterAccess policy internal

---

BitFaster.Caching.UnitTests/Scheduler/BackgroundSchedulerTests.cs

Since switching to the default scheduler, this test has failed to stop twice. Async/await and time are not stable in xunit. As a first step to avoid intermittent failures, try to increase the timeout.
```
System.Exception : Failed to stop
at BitFaster.Caching.UnitTests.Scheduler.BackgroundSchedulerTests.WhenDisposedRunsToCompletion() in D:\a\BitFaster.Caching\BitFaster.Caching\BitFaster.Caching.UnitTests\Scheduler\BackgroundSchedulerTests.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
```

Increase timeout for background scheduler test

---

BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentTLruTests.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs

`TrimExpired()` and `TrimLiveItems()` can now mark `isWarm == false`.

Mark LRU as cold during trim

---

BitFaster.Caching.UnitTests/Atomic/AtomicFactoryTests.cs
BitFaster.Caching/Atomic/AtomicFactory.cs

When `valueFactory` fails, all the threads queuing on the lock inside `Initializer` will call `valueFactory` one by one. If 100 threads are queued, and the valueFactory takes 1 second to fail, the `valueFactory` will be invoked 100 times, and the last thread in the list will wait for 100 seconds before getting the exception. This is a [lock convoy](https://en.wikipedia.org/wiki/Lock_convoy) introducing unnecessary overhead.
With this change, the 100 queued threads will all instantly fail with the same exception, and there will be 100 times fewer `valueFactory` calls. Subsequent calls will start from scratch.
This solution is adapted from `LazyWithRetry` here:
https://stackoverflow.com/a/72579523/131345

Mitigate lock convoys when AtomicFactory throws

---

BitFaster.Caching/Atomic/AtomicFactory.cs

Not able to detect coverage for closing }, so delete braces in this case.

Fix code coverage anomaly

---

BitFaster.Caching.UnitTests/Atomic/AtomicFactoryTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentLruAfterAccessTests.cs

- AtomicFactoryTests: Repeat test and count the number of times the condition we are interested in occurred. 
- ConcurrentLfuAfterAccess: move cache creation out of the timed region, and execute the methods under test up front. Attempt to eliminate delays from JITting code or cold instruction cache.

Stabilize tests

---

BitFaster.Caching.Benchmarks/BitFaster.Caching.Benchmarks.csproj
BitFaster.Caching.Benchmarks/DataStructureBenchmarks.cs
BitFaster.Caching.Benchmarks/DisposerBench.cs
BitFaster.Caching.Benchmarks/DrainBenchmarks.cs
BitFaster.Caching.Benchmarks/Lfu/LfuJustGetOrAdd.cs
BitFaster.Caching.Benchmarks/Lru/LruAsyncGet.cs
BitFaster.Caching.Benchmarks/Lru/LruCycleBench.cs
BitFaster.Caching.Benchmarks/Lru/LruJustGetOrAdd.cs
BitFaster.Caching.Benchmarks/Lru/LruJustTryGet.cs
BitFaster.Caching.Benchmarks/Lru/LruMultiGet.cs
BitFaster.Caching.Benchmarks/Lru/LruZipDistribution.cs
BitFaster.Caching.Benchmarks/Lru/TLruTimeBenchmark.cs
BitFaster.Caching.Benchmarks/TimeBenchmarks.cs
BitFaster.Caching.Benchmarks/ValueFactoryBenchmarks.cs
BitFaster.Caching.ThroughputAnalysis/Host.cs

Enable tools to run cleanly on Linux and MacOS:
- Detect windows OS before native windows call in ThroughputAnalysis
- Conditional compile for Benchmarks to avoid .NET Framework and DisassemblyDiagnoser

Detect windows OS before native windows call in ThroughputAnalysis

---

BitFaster.Caching/BitFaster.Caching.csproj
Tools/TrimVerification/BitFaster.Trimmed.sln
Tools/TrimVerification/BitFaster.Trimmed/BitFaster.Trimmed.csproj
Tools/TrimVerification/BitFaster.Trimmed/Program.cs
Tools/TrimVerification/BitFaster.Trimmed/test.cmd

Based on:
https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming?pivots=dotnet-6-0
Able to publish a trimmed console app with BitFaster.Caching as the root assembly without error. Test project included in the tools directory.

Enable AOT trimming

---

BitFaster.Caching.UnitTests/Lru/ConcurrentLruSoakTests.cs

Cover 2 scenarios:
- Cache is warm (cover branches in warm cycle method)
- Cache is cold (cover branches in the warmup cycle method)

Soak ConcurrentLru clear

---

BitFaster.Caching.UnitTests/Lru/AfterAccessPolicyTests.cs
BitFaster.Caching.UnitTests/Lru/DiscretePolicyTests.cs
BitFaster.Caching/Lru/AfterAccessPolicy.cs
BitFaster.Caching/Lru/ConcurrentLru.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs
BitFaster.Caching/Lru/DiscreteItemPolicy.cs
BitFaster.Caching/Lru/DiscretePolicy.cs

File names/class names out of sync since removing #ifdefs and switching to Duration.

Fix policy names

---

.github/workflows/benchpr.yml
BitFaster.Caching.HitRateAnalysis/Analysis.cs
BitFaster.Caching.HitRateAnalysis/Arc/Runner.cs
BitFaster.Caching.HitRateAnalysis/Arc/RunnerConfig.cs
BitFaster.Caching.HitRateAnalysis/BitFaster.Caching.HitRateAnalysis.csproj
BitFaster.Caching.HitRateAnalysis/Glimpse/Runner.cs
BitFaster.Caching.HitRateAnalysis/PlotExt.cs
BitFaster.Caching.HitRateAnalysis/Wikibench/Runner.cs
BitFaster.Caching.ThroughputAnalysis/BitFaster.Caching.ThroughputAnalysis.csproj
BitFaster.Caching.ThroughputAnalysis/Exporter.cs
BitFaster.Caching.ThroughputAnalysis/Runner.cs
Tools/BenchPlot/BenchPlot.csproj
Tools/BenchPlot/BenchmarkData.cs
Tools/BenchPlot/PlotExt.cs
Tools/BenchPlot/Program.cs
Tools/BenchPlot/TimeParser.cs
Tools/Tools.sln

Use Plotly.NET:
- Hit rate analysis plots charts as part of output
- Throughput analysis plots charts as part of output
- Benchmarks plots are produced as a post processing step in the GitHub action via a command line application that processes the output .csv files
Examples:

Automate plots

---

BitFaster.Caching.ThroughputAnalysis/CacheFactory.cs
BitFaster.Caching.ThroughputAnalysis/Exporter.cs
BitFaster.Caching.ThroughputAnalysis/Runner.cs

X axis is a mess when there are > 100 threads. Instead, use an integer so that plotly automatically selects x axis increments.
Before:
After:

Plot throughput charts with integer thread count

---

BitFaster.Caching.UnitTests/Lru/AfterAccessPolicyTests.cs
BitFaster.Caching.UnitTests/Lru/TLruTickCount64PolicyTests .cs
BitFaster.Caching/Duration.cs
BitFaster.Caching/Lru/AfterAccessPolicy.cs
BitFaster.Caching/Lru/TLruLongTicksPolicy.cs
BitFaster.Caching/Lru/Time.cs

Previously the maximum settable expiry time depended on the build target. Instead, use the maximum value determined to be settable on all tested platforms: MacOS using `Stopwatch.GetTimestamp` as the time source.

Consolidate maximum time to expire

---

BitFaster.Caching/Lfu/ConcurrentLfu.cs

Volatile read before try enter lock. This is slightly faster in the benchmark.

Volatile read LFU drain status

---

BitFaster.Caching.UnitTests/BitOpsTests.cs
BitFaster.Caching/BitOps.cs

Required for TimerWheel in https://github.com/bitfaster/BitFaster.Caching/pull/516, keep internal for now.

Add TrailingZeroCount and LongCeilingPowerOfTwo

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuSoakTests.cs
BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuTests.cs
BitFaster.Caching/BitFaster.Caching.csproj
BitFaster.Caching/Lfu/ConcurrentLfu.cs
BitFaster.Caching/Lfu/LfuNode.cs
BitFaster.Caching/Lfu/NodePolicy.cs

To prepare for time-based expiry in https://github.com/bitfaster/BitFaster.Caching/pull/516, add the extension points for different node type and policy.
Considerations:
- Keep implementation details internal, only expose ConcurrentLfu
- Since LfuNode is used extensively in arrays (buffers), ensure the array type is sealed to avoid array covariance check on write.
- Preserve existing perf without any regression. Options are:
- Make ConcurrentLfuCore a base class similar to ConcurrentLruCore core. This means that all types involved in the inheritance chain must be public, and the consumer sees all the messy generics.
- Make ConcurrentLfuCore a class as a data member of ConcurrentLfu. This introduces another method call that appears to incur overhead even when inlnied.
- Make …

Extract ConcurrentLfuCore with generic node and policy

---

BitFaster.Caching.ThroughputAnalysis/BitFaster.Caching.ThroughputAnalysis.csproj
BitFaster.Caching.ThroughputAnalysis/ConfigFactory.cs
BitFaster.Caching.ThroughputAnalysis/Exporter.cs
BitFaster.Caching.ThroughputAnalysis/FastZipf.cs
BitFaster.Caching.ThroughputAnalysis/Format.cs
BitFaster.Caching.ThroughputAnalysis/Host.cs
BitFaster.Caching.ThroughputAnalysis/MeasurementsStatistics.cs
BitFaster.Caching.ThroughputAnalysis/ParallelBenchmark.cs
BitFaster.Caching.ThroughputAnalysis/PowerPlan.cs
BitFaster.Caching.ThroughputAnalysis/Program.cs
BitFaster.Caching.ThroughputAnalysis/Runner.cs
BitFaster.Caching.ThroughputAnalysis/Stage.cs
BitFaster.Caching.ThroughputAnalysis/ThreadPoolInspector.cs
BitFaster.Caching.ThroughputAnalysis/ThroughputBenchConfig.cs
BitFaster.Caching.ThroughputAnalysis/ThroughputBenchmark.cs
BitFaster.Caching/Lru/ClassicLru.cs

- Use BenchmarkDotNet's method to keep return values alive, mitigating dead code elimination for the return value from cache GetOrAdd. This reduces peak throughput by about 10%, likely due to the extra non-inlined method.
- Apply optimization option to test execution method.
- Use Threads instead of Tasks. This is more stable, but MemoryCache results now have more extreme outliers due to unpredictable nature of background thread eviction.
- Replicate the BenchmarkDotNet main loop to determine when the result is stable, based on computing statistics from the results so far.
- Use Perfolizer to eliminate outliers from the result calculation - this eliminates some of the outliers from MemoryCache when the eviction thread is not scheduled. The update and evict scenarios provoke unbounded …

Throughput analysis v2.0

---

BitFaster.Caching/Buffers/MpscBoundedBuffer.cs
BitFaster.Caching/Buffers/StripedMpscBuffer.cs
BitFaster.Caching/Lfu/ConcurrentLfuCore.cs

The read and write buffer are both mp-sc (single consumer) - it is only valid for 1 thread to deque. Prior change switched from `Clear` allocating a new buffer to `TryTake` until empty. 
Clearing the buffers must be protected by the maintenance lock, otherwise two threads can effectively dequeue - this situation is provoked by a test causing the build to hang intermittently.

Clear buffers under lock

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuSoakTests.cs
BitFaster.Caching/Lfu/ConcurrentLfuCore.cs
BitFaster.Caching/Lfu/LfuNode.cs

- Evict removes via KVP, instead of just key. This prevents incorrect removal of nodes added to the dictionary when there are two nodes in the write buffer/LRUs with the same key. For example:
- Node 1 is added with key x
- Node 1 is removed, now exists only in write buffer + LRU list
- Node 2 is added with key x, and is also in the write buffer + LRU list
- Maintenance previously found node 1, and deleted key x from the dictionary detaching node 2. Delete is now via KVP, so node 2 will not be deleted in this situation.
- Check for removed nodes during `EvictFromMain()`
- `Evict()` marks items as removed/deleted
- Revise Trim logic to use LRU count instead of the dictionary. If TryRemove has been called, the dictionary can contain fewer items than the LRU lists. First call `Maintenance()` …

Fix race in LFU maintenance for add-remove-add of the same key

---

BitFaster.Caching.UnitTests/Lru/ConcurrentTLruTests.cs
BitFaster.Caching/Lfu/ConcurrentLfuCore.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs

This fixes a small gap, and introduces an observability difference because TLRU tests previously used to the count to observe eviction. To fix this:
- Remove the abstract base class used for TLRU tests - this is no longer needed since introducing `Duration` and having a single implementation of `TLruLongTicksPolicy`.
- Change the tests to use `ConcurrentTLru`, and verify expiry via the internal queue counters which are part of the public API.

LRU enumeration should not return expired/removed items

---

BitFaster.Caching.UnitTests/ReferenceCountTests.cs

This was highlighted as potentially incorrect, verify it works as expected.

Nullability: verify ReferenceCount<object>(null) GetHashCode

---

.github/workflows/benchpr.yml
.github/workflows/gate.yml

Update actions to avoid dependency on deprecated node version:

Update github actions

---

BitFaster.Caching.HitRateAnalysis/Arc/Runner.cs
BitFaster.Caching.HitRateAnalysis/MemoryCacheAdaptor.cs
BitFaster.Caching.HitRateAnalysis/ThreadPoolInspector.cs

MemoryCache enqueues cache maintenance to the thread pool asynchronously. This leads to non-deterministic results in the hit rate tests, depending on whether cache maintenance has run.
ConcurrentLfu tests are run with a foreground scheduler (no background maintenance) to avoid this problem.
To make the tests fair, wait for all thread pool tasks to complete each time there is a MemoryCache read. This achieves stable results with a small penalty.
Thread.Sleep(1) increases the test runtime for glimpse from 0.31 secs to about 15 secs - i.e. 4700% slower. Repeated Thread.Sleep(0) is only about 25% slower.

Drain threads for memory cache hit rate analysis

---

.github/workflows/gate.yml
.github/workflows/testreport.yml

- Extract test report workflow as documented [here](https://github.com/phoenix-actions/test-reporting?tab=readme-ov-file#recommended-setup-for-public-repositories) for 'Recommended setup for public repositories'.
- Updated to v15
For now, only move the .NET 4.8 tests as a first step.

Update test action in gate.yml

---

BitFaster.Caching/IAsyncCacheExt.cs
BitFaster.Caching/Lfu/ConcurrentLfu.cs
BitFaster.Caching/Lfu/ConcurrentTLfu.cs
BitFaster.Caching/Lru/ClassicLru.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs

Similar to PR #566, enable users of .NET Standard to combine:
- `ConcurrentLruBuilder.WithExpireAfter()`
- New methods added to `ICacheAsync` since v2.0

Add IAsyncCacheExt

---

BitFaster.Caching.Benchmarks/TimeBenchmarks.cs
BitFaster.Caching.UnitTests/DurationTests.cs
BitFaster.Caching.UnitTests/Lru/AfterAccessPolicyTests.cs
BitFaster.Caching.UnitTests/Lru/DiscretePolicyTests.cs
BitFaster.Caching.UnitTests/Lru/TLruTickCount64PolicyTests .cs
BitFaster.Caching/Duration.cs

This brings a more noticeable gain, building on #540. The OS check is not a JIT intrinsic until .NET8, so repeated checks are a penalty. As a follow up, need to verify whether windows bench was regressed and whether the OS check is ultimately elided by the JIT.
With this fix (static readonly bool):
| Method                   | Mean      | Error     | StdDev    | Ratio | Allocated | 
|------------------------- |----------:|----------:|----------:|------:|----------:|
| ConcurrentDictionary     |  4.023 ns | 0.0114 ns | 0.0089 ns |  1.00 |         - | 
| FastConcurrentTLru       | 14.995 ns | 0.0046 ns | 0.0036 ns |  3.73 |         - | 
| FastConcLruAfterAccess   | 17.534 ns | 0.0465 ns | 0.0388 ns |  4.36 |         - | 
| FastConcLruAfter         | 20.035 ns | 0.0061 ns | 0.0051 ns |  4.98 …

Static OS check to select clock

---

BitFaster.Caching.UnitTests/DurationTests.cs
BitFaster.Caching.UnitTests/Lru/TlruStopwatchPolicyTests.cs
BitFaster.Caching/Duration.cs

Note; this introduces a test hole: there are currently no tests that verify .NET standard when it is not running on Windows (we only execute NET4.8 on Windows to test .NET Standard). Since code coverage analysis only runs for .NET Core build targets, this is not observable in the code coverage report.

P/Invoke TickCount64 for .NET Standard on Windows

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentTLfuTests.cs
BitFaster.Caching/Lfu/ConcurrentLfuCore.cs
BitFaster.Caching/Lfu/NodePolicy.cs

From the discussion here https://github.com/bitfaster/BitFaster.Caching/pull/516, this is the repro:
```cs
[Fact]
public void Repro()
{ 
var cache = new ConcurrentLfuBuilder<int, int>()
.WithCapacity(10)
.WithExpireAfterAccess(TimeSpan.FromSeconds(5))
.Build();
cache.AddOrUpdate(1, 1);
Thread.Sleep(4000);
cache.TryGet(1, out var value).Should().BeTrue(); // maintenance doesn't run here
Thread.Sleep(2000);
cache.TryGet(1, out value).Should().BeTrue();
cache.TryGet(1, out value).Should().BeTrue();
}
```
Since maintenance only runs when the read buffer is full, expiry time is never updated.
Solution:
- Policy computes new expiry time at the call site (either on read or update), instead of during maintenance.
- For read, `IsExpired` has just been called, so we can piggyback on the current …

LFU after access fails to update expiry when read buffer is not full

---

BitFaster.Caching.ThroughputAnalysis/SizeExec.sh
BitFaster.Caching.ThroughputAnalysis/ThroughputBenchmark.cs

Enable running faster with larger cache sizes. Read test with 10000000 elements is often taking several hours for each test pass, this drops max runtime to more like 15 minutes.

Tune throughput test parameters

---

BitFaster.Caching.UnitTests/Lru/ConcurrentLruSoakTests.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs

There is a lock in `TryUpdate` to prevent concurrent updates, but no item lock on `TryRemove(kvp)`. No lock is needed for `TryRemove(key)` because updates to the value do not affect the outcome - key should always be removed. The value is important in the kvp variant however, where the equivalent lock was missed leading to a race when the value changes between finding the existing LruItem and removing it.

Fix race in LRU concurrent update and TryRemove(kvp)

---

BitFaster.Caching.UnitTests/Lfu/ConcurrentLfuSoakTests.cs
BitFaster.Caching/Lfu/ConcurrentLfuCore.cs

Apply equivalent fix from #616 to `ConcurrentLfu`.

Fix race in LFU concurrent update and TryRemove(kvp)

---

BitFaster.Caching.Benchmarks/Lfu/LfuJustGetOrAdd.cs
BitFaster.Caching.Benchmarks/Lru/LruJustGetOrAdd.cs

This appears to have little effect on the result, but is best practice as mentioned [here](https://benchmarkdotnet.org/articles/guides/good-practices.html#avoid-dead-code-elimination).

benchmarks avoid dead code elimination

---

BitFaster.Caching.Benchmarks/Lru/LruJustGetOrAdd.cs

This is causing the assembler code per bench to fail.

Fix bench return type

---

BitFaster.Caching/Lru/AfterAccessPolicy.cs
BitFaster.Caching/Lru/DiscretePolicy.cs
BitFaster.Caching/Lru/LruItem.cs
BitFaster.Caching/Lru/LruPolicy.cs
BitFaster.Caching/Lru/TLruLongTicksPolicy.cs
BitFaster.Caching/Lru/TlruDateTimePolicy.cs
BitFaster.Caching/Lru/TlruTicksPolicy.cs

`LruItem.WasAccessed` was previously `volatile` to ensure that thread A marking an item as accessed is visible to thread B that is cycling the cache. Under the covers, `volatile` equates to half fence for reads and writes.
From the [.NET memory model](https://github.com/dotnet/runtime/blob/main/docs/design/specs/Memory-model.md):
- **Volatile reads** have "acquire semantics" - no read or write that is later in the program order may be speculatively executed ahead of a volatile read. 
- **Volatile writes** have "release semantics" - the effects of a volatile write will not be observable before effects of all previous, in program order, reads and writes become observable.
- **Full-fence** operations have "full-fence semantics" - effects of reads and writes must be observable no later or no …

Optimize ConcurrentLru read throughput

---

BitFaster.Caching.HitRateAnalysis/BitFaster.Caching.HitRateAnalysis.csproj

Running on .NET8 with server GC significantly improves runtime.

Optimize hit rate analysis

---

.github/workflows/benchpr.yml

https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

update artifact actions

---

BitFaster.Caching.UnitTests/Lru/ConcurrentLruTests.cs
BitFaster.Caching.UnitTests/Lru/ConcurrentTLruTests.cs
BitFaster.Caching.UnitTests/Lru/DiscretePolicyTests.cs
BitFaster.Caching.UnitTests/Lru/LruPolicyTests.cs
BitFaster.Caching.UnitTests/Lru/TLruTickCount64PolicyTests .cs
BitFaster.Caching.UnitTests/Lru/TlruDateTimePolicyTests.cs
BitFaster.Caching.UnitTests/Lru/TlruStopwatchPolicyTests.cs
BitFaster.Caching.UnitTests/Lru/TlruTicksPolicyTests.cs
BitFaster.Caching/Lru/ConcurrentLruCore.cs
BitFaster.Caching/Lru/DiscretePolicy.cs
BitFaster.Caching/Lru/LruPolicy.cs
BitFaster.Caching/Lru/TLruLongTicksPolicy.cs
BitFaster.Caching/Lru/TlruDateTimePolicy.cs
BitFaster.Caching/Lru/TlruTicksPolicy.cs

When items are deleted, they remain in the internal queues until fully cycled out of cold. This is because the cycle/route methods do not inspect `WasDeleted`. Instead, purge them as items transition from queue to queue as part of cycle.
This change doesn't trigger double dispose/event due to the implementation of the `Move` method first attempting to remove the item from the dictionary:
```cs
[MethodImpl(MethodImplOptions.AggressiveInlining)]
private int Move(I item, ItemDestination where, ItemRemovedReason removedReason)
{
item.WasAccessed = false;
switch (where)
{
case ItemDestination.Warm:
this.warmQueue.Enqueue(item);
return Interlocked.Increment(ref this.counter.warm);
case ItemDestination.Cold:
this.coldQueue.Enqueue(item);
return Interlocked.Increment(ref this.counter.cold);
case …
```

Eagerly purge deleted items from internal LRU queues

---

BitFaster.Caching/Lru/Defaults.cs
BitFaster.Caching/Lru/LruPolicy.cs

This is just a readability thing. Use `Timeout.InfiniteTimeSpan` not `new TimeSpan(0, 0, 0, 0, -1)`.

Use Timeout.InfiniteTimeSpan

---

BitFaster.Caching/Lru/EqualCapacityPartition.cs

This eliminates three instances of variable shadowing and slightly simplifies the code.

Use auto-implemented properties

---

BitFaster.Caching.Benchmarks/BitFaster.Caching.Benchmarks.csproj
BitFaster.Caching/BitFaster.Caching.csproj
BitFaster.Caching/Lfu/ConcurrentLfuCore.cs

Take the `ConcurrentLfu` lock optimization from https://github.com/bitfaster/BitFaster.Caching/pull/638.
Benchmark shows lock try enter is slightly faster:
| Method     | Mean     | Error    | StdDev   | Ratio | Allocated |
|----------- |---------:|---------:|---------:|------:|----------:|
| UseMonitor | 17.88 ns | 0.235 ns | 0.220 ns |  1.00 |         - |
| UseLock    | 14.79 ns | 0.315 ns | 0.309 ns |  0.83 |         - |

Use System.Threading.Lock in ConcurrentLfu

---

.github/workflows/gate.yml

If any job in the build matrix fails due to an instability, it is not possible to re-run the individual job or the entire matrix.
Instead of `continue-on-error = true`, use  `fail-fast = false`:
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

fix build re-run
